// <auto-generated />
using System;
using FaultLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaultLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FaultLedgerDbContext))]
    [Migration("20260916214644_DurableProviderInbox")]
    partial class DurableProviderInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaultLedger.Infrastructure.Persistence.ProviderInboxRecord", b =>
                {
                    b.Property<Guid>("InboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("evidence");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<string>("NormalizedPayload")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_payload");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer")
                        .HasColumnName("payload_version");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("processing_status");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_event_id")
                        .UseCollation("C");

                    b.Property<Guid>("ProviderOperationCorrelation")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_operation_correlation");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_reference");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("InboxId")
                        .HasName("pk_provider_inbox");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_inbox_provider_event_id");

                    b.HasIndex("ProviderOperationCorrelation")
                        .HasDatabaseName("ix_provider_inbox_operation_correlation");

                    b.HasIndex("ProcessingStatus", "ReceivedAt")
                        .HasDatabaseName("ix_provider_inbox_processing");

                    b.ToTable("provider_inbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_provider_inbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_provider_inbox_event_type", "event_type IN ('Accepted', 'Completed', 'Rejected', 'Failed')");

                            t.HasCheckConstraint("ck_provider_inbox_payload_version", "payload_version = 1");

                            t.HasCheckConstraint("ck_provider_inbox_processing_status", "processing_status IN ('Pending', 'Processing', 'Processed', 'Failed')");
                        });
                });

            modelBuilder.Entity("FaultLedger.Infrastructure.Persistence.TransferRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("amount");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("FingerprintVersion")
                        .HasColumnType("integer")
                        .HasColumnName("fingerprint_version");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("C");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint")
                        .UseCollation("C");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_transfers_idempotency_key");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amount", "amount > 0 AND amount <= 99999999999999999999.99999999");

                            t.HasCheckConstraint("ck_transfers_client_reference", "client_reference COLLATE \"C\" ~ '^[A-Za-z0-9_.:-]{1,100}$'");

                            t.HasCheckConstraint("ck_transfers_currency", "currency COLLATE \"C\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_transfers_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_transfers_idempotency_key", "idempotency_key COLLATE \"C\" ~ '^[A-Za-z0-9_.:-]{1,128}$'");

                            t.HasCheckConstraint("ck_transfers_provider_reference", "(state IN ('Accepted', 'Completed') AND provider_reference IS NOT NULL AND provider_reference COLLATE \"C\" ~ '^[A-Za-z0-9_.:-]{1,100}$') OR (state NOT IN ('Accepted', 'Completed') AND provider_reference IS NULL)");

                            t.HasCheckConstraint("ck_transfers_request_fingerprint", "(request_fingerprint IS NULL AND fingerprint_version IS NULL) OR (request_fingerprint COLLATE \"C\" ~ '^[0-9a-f]{64}$' AND fingerprint_version = 1)");

                            t.HasCheckConstraint("ck_transfers_state_version", "(state = 'Created' AND version = 0) OR (state = 'ReadyToSubmit' AND version = 1) OR (state = 'Submitting' AND version = 2) OR (state IN ('Accepted', 'Failed') AND version IN (3, 4)) OR (state = 'Unknown' AND version = 3) OR (state = 'Completed' AND version IN (4, 5)) OR (state = 'ManualReview' AND version = 4)");

                            t.HasCheckConstraint("ck_transfers_timestamps", "updated_at >= created_at AND isfinite(created_at) AND isfinite(updated_at)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
