<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../FaultLedger.Application/FaultLedger.Application.csproj" />
    <ProjectReference Include="../FaultLedger.Domain/FaultLedger.Domain.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
